### ISSUE TITLE
project info

### ISSUE THREAD

**Issue by B0RJA** [spel-oe/gpr#1]
Thank you for sharing your work!

I am working on a VNA-based GPR and I was wondering if you have a web page or a document with the project details. The analysis part is quite clear but it would be very useful to know other aspects such as the design and fabrication of the antennas. 

Best regards,
Borja

**Comment by spel-oe** [comment]
At the moment all the available information is there in this repo. Still not more than a brain fart. Some extensive real world characterization of the setup is needed including testing the limits. If the tests are looking good I want to document everything in more detail.

The antenna used are some wide band PCB-antennas designed for that purpose. Since there is no optimal coupling/ transmission into the ground, this always be some kind of compromise.

**Comment by B0RJA** [comment]
thank you and keep up the good work!
